name = input("Enter your name: ")
age = input("Enter your age: ")
location = input("Enter your location:  ")
next_of_kin = input("Enter your next_of_kin: ")
spouse_name = input("Enter your spouse's name: ")
marriage_year = input("Enter your marriage_year: ")
marriage_month = input("Enter your marriage_month: ")
marriage_day = input("Enter your marriage_day: ")
occupation =input("Enter your occupation: ")
job_experience = input("Enter your job_experience: ")
number_of_kids = input("Enter your number_of_kids: ")
name_of_kids = input("Enter your name_of_kids: ")

print(name)
print(age)
print(location)
print(next_of_kin)
print(spouse_name)
print(marriage_year)
print(marriage_month)
print(marriage_day)
print(occupation)
print(job_experience)
print(number_of_kids)
print(name_of_kids)
